"""Writes src/voice-phrases.h from INTENTS in voice.py, so the plugin's "All voice commands"
window lists exactly what the listener knows. Run after editing INTENTS:  python app/gen_voice_phrases.py"""
import importlib.util, os, sys
here = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("voice", os.path.join(here, "voice.py"))
try:
    m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
except ImportError:
    # numpy may be missing on the build machine: read INTENTS out of the source instead
    src = open(os.path.join(here, "voice.py"), encoding="utf-8").read()
    ns = {}
    exec(src[src.index("INTENTS = {"):src.index("}\n", src.index("INTENTS = {")) + 2], ns)
    m = type("M", (), {"INTENTS": ns["INTENTS"]})
LABELS = [
    ("replay", "Instant replay", "plays the last highlight", "Kennel - instant replay"),
    ("clip", "Clip that", "saves a clip; the sentence after it becomes the title", "Kennel - clip that"),
    ("clip_replay", "Clip replay", "saves a clip and plays it back at once", "Kennel - clip that + instant replay"),
    ("dual", "Dual POV on", "the small second-POV window", "Kennel - force dual point of view"),
    ("dual_off", "Dual POV off", "", "Kennel - force dual point of view"),
    ("force", "Squad mate POV", "the chosen squad mate on stream now, downed or not", "Kennel - force squad mate point of view"),
    ("change", "Change squad mate", "the next one with a picture, or by name: \"show bouga\", \"switch to carranco\"", "Kennel - change squad mate point of view"),
    ("closest", "Closest squad mate", "the nearest one from the NEARBY list", "Kennel - show closest squad mate point of view"),
    ("me", "Back to me", "your own POV", "always on"),
    ("highlights", "Highlights", "plays the compilation of this stream's highlights", "always on"),
]
out = ["// Generated by app/gen_voice_phrases.py from app/voice.py - do not edit by hand.", "#pragma once", "#include \"i18n.h\" // TX_NOOP: the titles and descriptions are translated where shown (txv)", "",
       "struct VoicePhraseGroup {", "\tconst char *cmd;", "\tconst char *title;", "\tconst char *what;",
       "\tconst char *gate;", "\tconst char *phrases; // separated by |", "};", "",
       "static const VoicePhraseGroup kVoicePhrases[] = {"]
def tq(s): return q(s) if not s else "TX_NOOP(" + q(s) + ")"
def q(s): return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
for cmd, title, what, gate in LABELS:
    ph = m.INTENTS.get(cmd, [])
    if cmd == "change":
        ph = ph + ["show <name>", "switch to <name>", "put <name> on"]
    out.append("\t{%s, %s, %s, %s, %s}," % (q(cmd), tq(title), tq(what), tq(gate), q("|".join(ph))))
out += ["};", ""]
path = os.path.join(here, "..", "src", "voice-phrases.h")
open(path, "w", encoding="utf-8").write("\n".join(out))
print("wrote", os.path.relpath(path), "with", len(LABELS), "groups")
