// Generated by app/gen_voice_phrases.py from app/voice.py - do not edit by hand.
#pragma once
#include "i18n.h" // TX_NOOP: the titles and descriptions are translated where shown (txv)

struct VoicePhraseGroup {
	const char *cmd;
	const char *title;
	const char *what;
	const char *gate;
	const char *phrases; // separated by |
};

static const VoicePhraseGroup kVoicePhrases[] = {
	{"replay", TX_NOOP("Instant replay"), TX_NOOP("plays the last highlight"), TX_NOOP("Kennel - instant replay"),
	 "replay|instant replay|play that back|play it back|run it back|play it again|rewind|show the replay|replay that"},
	{"clip", TX_NOOP("Clip that"), TX_NOOP("saves a clip; the sentence after it becomes the title"),
	 TX_NOOP("Kennel - clip that"),
	 "clip|clip that|clip it|clip this|save that|save clip|save the clip|record that|clip him|clip the last bit"},
	{"clip_replay", TX_NOOP("Clip replay"), TX_NOOP("saves a clip and plays it back at once"),
	 TX_NOOP("Kennel - clip that + instant replay"),
	 "clip replay|clip and replay|clip then replay|clip that and replay|save and replay|clip it and replay|replay clip|clip and play it back"},
	{"dual", TX_NOOP("Dual POV on"), TX_NOOP("the small second-POV window"),
	 TX_NOOP("Kennel - force dual point of view"),
	 "dual|dual pov|dual point of view|force dual|split screen|both povs|two povs|dual on|go dual|both pov|both|both of us|picture in picture|two pov"},
	{"dual_off", TX_NOOP("Dual POV off"), "", TX_NOOP("Kennel - force dual point of view"),
	 "dual off|dual pov off|stop dual|single pov|end dual|turn off dual"},
	{"force", TX_NOOP("Squad mate POV"), TX_NOOP("the chosen squad mate on stream now, downed or not"),
	 TX_NOOP("Kennel - force squad mate point of view"),
	 "force squad mate|force squad mate pov|squad mate pov|show squad mate|show my squad mate|show his pov|show her pov|show their pov|teammate pov|switch to squad mate|squad mate point of view|show squad mate point of view|go to squad mate"},
	{"change", TX_NOOP("Change squad mate"),
	 TX_NOOP("the next one with a picture, or by name: \"show bouga\", \"switch to carranco\""),
	 TX_NOOP("Kennel - change squad mate point of view"),
	 "change squad mate|next squad mate|switch squad mate|other squad mate|next pov|change pov|change point of view|swap squad mate|next one|someone else|change squad mate point of view|switch pov|switch povs|swap pov|switch the pov|switch point of view|next point of view|other pov|show <name>|switch to <name>|put <name> on"},
	{"closest", TX_NOOP("Closest squad mate"), TX_NOOP("the nearest one from the NEARBY list"),
	 TX_NOOP("Kennel - show closest squad mate point of view"),
	 "closest|nearest|show closest|closest squad mate|nearest squad mate|who is closest|whos closest|show the closest pov|closest pov|nearest pov|show closest squad mate point of view"},
	{"me", TX_NOOP("Back to me"), TX_NOOP("your own POV"), TX_NOOP("always on"),
	 "back|my pov|me|back to me|my point of view|show me|stop|my screen|go back|back to my pov"},
	{"highlights", TX_NOOP("Highlights"), TX_NOOP("plays the compilation of this stream's highlights"),
	 TX_NOOP("always on"), "highlights|play highlights|compilation|montage|play the compilation"},
};
